apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: r3a
  labels:
    app: postgres-external
spec:
  clusterIP: None
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: r3a
  labels:
    app: postgres-external
subsets:
  - addresses:
      - ip: 192.168.0.70  # IP do host onde est√° o Postgres
    ports:
      - name: pg
        port: 5432
