apiVersion: v1
kind: Namespace
metadata:
  name: r3a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: r3a-node-admin
  namespace: r3a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: r3a-node-admin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch","patch","update","label","annotate"]  # patch/update cobrem label/annotate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: r3a-node-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: r3a-node-admin
subjects:
  - kind: ServiceAccount
    name: r3a-node-admin
    namespace: r3a
